### ISSUE TITLE
when i build the rosbag2-rolling,i meet this problem. I dont understand why need .json file for msg?

### ISSUE THREAD

**Issue by Xen0sWang** [ros2/rosbag2#1405]
```
stderr: rosbag2_interfaces                                                                                                                                                   
Traceback (most recent call last):
  File "/home/udeer/Downloads/rosidl/install/rosidl_generator_type_description/lib/rosidl_generator_type_description/rosidl_generator_type_description", line 50, in <module>
    sys.exit(main())
  File "/home/udeer/Downloads/rosidl/install/rosidl_generator_type_description/lib/rosidl_generator_type_description/rosidl_generator_type_description", line 46, in main
    generate_type_hash(args.generator_arguments_file)
  File "/home/udeer/Downloads/rosidl/install/rosidl_generator_type_description/lib/python3.8/site-packages/rosidl_generator_type_description/__init__.py", line 162, in generate_type_hash
    with include_path.open('r') as include_file:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/udeer/Downloads/rcl_interfaces/install/builtin_interfaces/share/builtin_interfaces/msg/Duration.json'
make[2]: *** [CMakeFiles/rosbag2_interfaces__rosidl_generator_type_description.dir/build.make:91：rosidl_generator_type_description/rosbag2_interfaces/msg/ReadSplitEvent.json] 错误 1
make[1]: *** [CMakeFiles/Makefile2:329：CMakeFiles/rosbag2_interfaces__rosidl_generator_type_description.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2
---
Failed   <<< rosbag2_interfaces [6.47s, exited with code 2]
Aborted  <<< rosbag2_storage [7.33s]                                                                                                                    
Aborted  <<< shared_queues_vendor [9.49s]                                                                            
Aborted  <<< zstd_vendor [10.9s]                                    
                                  
Summary: 2 packages finished [11.1s]
  1 package failed: rosbag2_interfaces
  3 packages aborted: rosbag2_storage shared_queues_vendor zstd_vendor
  2 packages had stderr output: rosbag2_interfaces zstd_vendor
  12 packages not processed
```

**Comment by emersonknapp** [comment]
It looks like you're building against an older Rolling release bundle you downloaded from somewhere? There was a breaking update in message code generation before the Iron release that creates a new intermediate `.json` file for use by code generation.

You will need a newer binary bundle, or to build entirely from source, if you want to build rosbag2 rolling branch.

Closing for now as an unsupported use case, feel free to reopen if I've missed something.
