### ISSUE TITLE
ImportError: libyaml-cpp.so.0.6 / import-failing-even-with-library-present-on-the-system

### ISSUE THREAD

**Issue by hannes56a** [ros2/rosbag2#759]
Hey all,
I installed rosbag2 in my docker image (ros:eloquent) as descripted with apt-get (without rosbridge...)

When I try to use it (ros2 bag record -a) I have the following error:

```
root@baKIraspberrypicoral01:/# ros2 bag record -a
Traceback (most recent call last):
  File "/opt/ros/eloquent/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.8.8', 'console_scripts', 'ros2')()
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2cli/cli.py", line 69, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2bag/command/bag.py", line 40, in main
    return extension.main(args=args)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2bag/verb/record.py", line 83, in main
    from rosbag2_transport import rosbag2_transport_py
  File "/opt/ros/eloquent/lib/python3.6/site-packages/rosbag2_transport/__init__.py", line 32, in <module>
    rosbag2_transport_py = _import('._rosbag2_transport_py')
  File "/opt/ros/eloquent/lib/python3.6/site-packages/rosbag2_transport/__init__.py", line 21, in _import
    return importlib.import_module(name, package='rosbag2_transport')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libyaml-cpp.so.0.6: cannot open shared object file: No such file or directory
The C extension '/opt/ros/eloquent/lib/python3.6/site-packages/rosbag2_transport/_rosbag2_transport_py.cpython-36m-arm-linux-gnueabihf.so' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
```

can someone help me please?

**Comment by emersonknapp** [comment]
I'm sorry, but `eloquent` is no longer a supported ROS distribution - it reached EOL in November 2020. Somebody on answers.ros.org may be able to help you there, though - that is the most appropriate forum for general debugging/usage questions.
